# suppress inspection "SpringBootApplicationProperties" for whole file

# Import
spring.config.import=optional:classpath:/datasource-local.properties,optional:classpath:/application.properties

# Attachment
kr.me.seesaw.filepath=E:/IdeaProjects/attachments/daejeonstickybook

# JWT
jwt.secret.key=1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()
