# suppress inspection "SpringBootApplicationProperties" for whole file

# Import
spring.config.import=optional:classpath:/datasource-test.properties,optional:classpath:/application.properties

# Spring security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.security.user.name=test
spring.security.user.password=test

# Attachment
kr.me.seesaw.filepath=YOUR_PATH

# h2
spring.h2.console.enabled=true
