# suppress inspection "SpringBootApplicationProperties" for whole file

# Import
spring.config.import=optional:classpath:/datasource-test.properties,optional:classpath:/application.properties

# Attachment
kr.me.seesaw.filepath=/Users/doyevskyi/IdeaProjects/attachments/daejeonstickybook/

# h2
spring.h2.console.enabled=true

# JWT
jwt.secret.key=1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()