# suppress inspection "SpringBootApplicationProperties" for whole file

# Import
spring.config.import=optional:classpath:/datasource-test.properties,optional:classpath:/application.properties

# Attachment
kr.me.seesaw.filepath=YOUR_PATH

# h2
spring.h2.console.enabled=true
